apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
commonLabels:
  variant: production
namespace: production
bases:
- ../../base
images:
  - name: webapp-backend
    newName: europe-west8-docker.pkg.dev/acquired-voice-363315/hello-repo/webapp-sample-backend
    newTag: v1
  - name: webapp-frontend
    newName: europe-west8-docker.pkg.dev/acquired-voice-363315/hello-repo/webapp-sample-frontend
    newTag: v1

#patchesStrategicMerge:
#- deployment-frontend.yaml
#- deployment-backend.yaml
