apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: webapp

resources:
- deployment-backend.yaml
- deployment-frontend.yaml
- backend-service.yaml
- frontend-service.yaml
- ingress.yaml
